import re
f = open("backend/src/find_api/core/storage_local.py", "r")
c = f.read()
f.close()
c = c.replace("            with open(full_path, \"wb\") as f:\n                f.write(file_data)", "            def _write():\n                with open(full_path, \"wb\") as f:\n                    f.write(file_data)\n            await asyncio.to_thread(_write)")
c = c.replace("            with open(full_path, \"rb\") as f:\n                data = f.read()", "            def _read():\n                with open(full_path, \"rb\") as f:\n                    return f.read()\n            data = await asyncio.to_thread(_read)")
f = open("backend/src/find_api/core/storage_local.py", "w")
f.write(c)
f.close()
print("to_thread count:", c.count("to_thread"))
